### ISSUE TITLE
Fix or Remove campfire and smoker recipes

### ISSUE THREAD

**Issue by Dark-Shadow65** [Dark-Shadow65/Kingdoms-and-Castles-Datapack#39]

**Comment by Harlon26** [comment]
can craft but they wont cook food

**Comment by Dark-Shadow65** [comment]
Yes, you will be able to craft the campfire and smoker, but you can't use them

**Comment by Dark-Shadow65** [comment]
Disabling the vanilla recipes seemed to do this without needing any other fixes. I should have checked if the recipes work before opening this issue lol
